#import "ChartViewController.h"
#import "AboutViewController.h"
#import "AirportMapViewController.h"
#import "ContentManagerViewController.h"
#import "PackArchiveInstaller.h"
#import "WeatherViewController.h"
#import <QuartzCore/QuartzCore.h>

@interface ChartViewController () <UIActionSheetDelegate>
@property(nonatomic, retain) UIView *topBar;
@property(nonatomic, retain) UIView *footer;
@property(nonatomic, retain) UIView *categoryRail;
@property(nonatomic, retain) UIButton *airportButton;
@property(nonatomic, retain) UILabel *airportCaptionLabel;
@property(nonatomic, retain) UITextField *searchField;
@property(nonatomic, retain) UIButton *searchButton;
@property(nonatomic, retain) UIButton *settingsButton;
@property(nonatomic, retain) UIButton *mapButton;
@property(nonatomic, retain) UIButton *weatherButton;
@property(nonatomic, retain) UIButton *fitButton;
@property(nonatomic, retain) UIButton *previousButton;
@property(nonatomic, retain) UIButton *nextButton;
@property(nonatomic, retain) UILabel *titleLabel;
@property(nonatomic, retain) UILabel *statusLabel;
@property(nonatomic, retain) UITableView *categoryTable;
@property(nonatomic, retain) UITableView *airportTable;
@property(nonatomic, retain) UITableView *chartTable;
@property(nonatomic, retain) UIScrollView *scrollView;
@property(nonatomic, retain) UIImageView *imageView;
@property(nonatomic, retain) NSArray *allAirports;
@property(nonatomic, retain) NSArray *airports;
@property(nonatomic, retain) NSArray *categories;
@property(nonatomic, retain) NSArray *chartGroups;
@property(nonatomic, retain) NSDictionary *selectedAirport;
@property(nonatomic, retain) NSDictionary *selectedChart;
@property(nonatomic, retain) NSArray *chartPages;
@property(nonatomic, retain) NSString *packJobID;
@property(nonatomic, assign) NSInteger selectedCategoryIndex;
@property(nonatomic, assign) NSInteger pageIndex;
@property(nonatomic, assign) NSTimeInterval packStartedAt;
@property(nonatomic, assign) CGSize lastViewerSize;
@property(nonatomic, assign) CGSize lastCategoryLayoutSize;
@property(nonatomic, assign) BOOL chartListVisible;
@end

@implementation ChartViewController
@synthesize topBar=_topBar,footer=_footer,categoryRail=_categoryRail,airportButton=_airportButton,airportCaptionLabel=_airportCaptionLabel,searchField=_searchField,searchButton=_searchButton,settingsButton=_settingsButton,mapButton=_mapButton,weatherButton=_weatherButton,fitButton=_fitButton,previousButton=_previousButton,nextButton=_nextButton,titleLabel=_titleLabel,statusLabel=_statusLabel;
@synthesize categoryTable=_categoryTable,airportTable=_airportTable,chartTable=_chartTable,scrollView=_scrollView,imageView=_imageView;
@synthesize allAirports=_allAirports,airports=_airports,categories=_categories,chartGroups=_chartGroups,selectedAirport=_selectedAirport,selectedChart=_selectedChart,chartPages=_chartPages,packJobID=_packJobID;
@synthesize selectedCategoryIndex=_selectedCategoryIndex,pageIndex=_pageIndex,packStartedAt=_packStartedAt,lastViewerSize=_lastViewerSize,lastCategoryLayoutSize=_lastCategoryLayoutSize,chartListVisible=_chartListVisible;

- (CAGradientLayer *)gradient:(CGRect)frame top:(CGFloat)top bottom:(CGFloat)bottom { CAGradientLayer *layer=[CAGradientLayer layer];layer.frame=frame;layer.colors=[NSArray arrayWithObjects:(id)[UIColor colorWithWhite:top alpha:1].CGColor,(id)[UIColor colorWithWhite:bottom alpha:1].CGColor,nil];return layer; }
- (CAGradientLayer *)selectionGradient:(CGRect)frame { CAGradientLayer *layer=[CAGradientLayer layer];layer.frame=frame;layer.colors=[NSArray arrayWithObjects:(id)[UIColor colorWithRed:1 green:.55 blue:.48 alpha:1].CGColor,(id)[UIColor colorWithRed:1 green:.25 blue:.03 alpha:1].CGColor,(id)[UIColor colorWithRed:.72 green:.05 blue:.01 alpha:1].CGColor,nil];layer.locations=[NSArray arrayWithObjects:[NSNumber numberWithFloat:0],[NSNumber numberWithFloat:.55],[NSNumber numberWithFloat:1],nil];return layer; }
- (UIButton *)chromeButton:(NSString *)title action:(SEL)action { UIButton *button=[UIButton buttonWithType:UIButtonTypeCustom];button.layer.cornerRadius=5;button.layer.borderWidth=1;button.layer.borderColor=[UIColor blackColor].CGColor;[button setTitle:title forState:UIControlStateNormal];button.titleLabel.font=[UIFont boldSystemFontOfSize:13];[button addTarget:self action:action forControlEvents:UIControlEventTouchUpInside];return button; }
- (void)styleChromeButton:(UIButton *)button { if(button.layer.sublayers.count&&[[button.layer.sublayers objectAtIndex:0]isKindOfClass:[CAGradientLayer class]])[[button.layer.sublayers objectAtIndex:0]removeFromSuperlayer];[button.layer insertSublayer:[self gradient:button.bounds top:.46 bottom:.15] atIndex:0]; }
- (void)styleRailButton:(UIButton *)button { if(button.layer.sublayers.count&&[[button.layer.sublayers objectAtIndex:0]isKindOfClass:[CAGradientLayer class]])[[button.layer.sublayers objectAtIndex:0]removeFromSuperlayer];CAGradientLayer *shine=[self gradient:button.bounds top:.42 bottom:.09];shine.cornerRadius=9;[button.layer insertSublayer:shine atIndex:0];button.layer.cornerRadius=9;button.layer.borderWidth=1.5;button.layer.borderColor=[UIColor colorWithWhite:.72 alpha:1].CGColor;button.layer.shadowColor=[UIColor blackColor].CGColor;button.layer.shadowOpacity=.9;button.layer.shadowRadius=3;button.layer.shadowOffset=CGSizeMake(0,2);button.titleLabel.shadowColor=[UIColor blackColor];button.titleLabel.shadowOffset=CGSizeMake(0,-1); }
- (void)styleAirportButton { [self styleRailButton:self.airportButton]; }

- (void)viewDidLoad {
    [super viewDidLoad];self.view.backgroundColor=[UIColor colorWithWhite:.08 alpha:1];
    self.categoryRail=[[[UIView alloc]initWithFrame:CGRectZero]autorelease];self.categoryRail.backgroundColor=[UIColor colorWithWhite:.045 alpha:1];[self.view addSubview:self.categoryRail];
    self.airportButton=[self chromeButton:@"----" action:@selector(promptAirportCode)];self.airportButton.titleLabel.font=[UIFont boldSystemFontOfSize:16];self.airportButton.titleEdgeInsets=UIEdgeInsetsMake(17,0,0,0);[self.categoryRail addSubview:self.airportButton];
    self.airportCaptionLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];self.airportCaptionLabel.backgroundColor=[UIColor clearColor];self.airportCaptionLabel.text=@"AIRPORT ▾";self.airportCaptionLabel.textColor=[UIColor colorWithWhite:.72 alpha:1];self.airportCaptionLabel.textAlignment=NSTextAlignmentCenter;self.airportCaptionLabel.font=[UIFont boldSystemFontOfSize:8];self.airportCaptionLabel.shadowColor=[UIColor blackColor];self.airportCaptionLabel.shadowOffset=CGSizeMake(0,-1);self.airportCaptionLabel.userInteractionEnabled=NO;[self.airportButton addSubview:self.airportCaptionLabel];
    self.topBar=[[[UIView alloc]initWithFrame:CGRectZero]autorelease];[self.view addSubview:self.topBar];
    self.titleLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];self.titleLabel.backgroundColor=[UIColor clearColor];self.titleLabel.textColor=[UIColor whiteColor];self.titleLabel.textAlignment=NSTextAlignmentCenter;self.titleLabel.font=[UIFont boldSystemFontOfSize:20];self.titleLabel.shadowColor=[UIColor blackColor];self.titleLabel.shadowOffset=CGSizeMake(0,-1);self.titleLabel.text=@"SkyCharts Offline Charts";[self.topBar addSubview:self.titleLabel];
    self.settingsButton=[self chromeButton:@"⚙" action:@selector(openPackMenu)];self.settingsButton.titleLabel.font=[UIFont boldSystemFontOfSize:25];[self.topBar addSubview:self.settingsButton];
    self.mapButton=[self chromeButton:@"MAP" action:@selector(openAirportMap)];self.mapButton.titleLabel.font=[UIFont boldSystemFontOfSize:12];[self.topBar addSubview:self.mapButton];
    self.weatherButton=[self chromeButton:@"Wx" action:@selector(showWeather)];self.weatherButton.titleLabel.font=[UIFont boldSystemFontOfSize:15];[self.categoryRail addSubview:self.weatherButton];

    self.categoryTable=[[[UITableView alloc]initWithFrame:CGRectZero style:UITableViewStylePlain]autorelease];self.categoryTable.backgroundColor=[UIColor colorWithWhite:.07 alpha:1];self.categoryTable.separatorStyle=UITableViewCellSeparatorStyleNone;self.categoryTable.scrollEnabled=NO;self.categoryTable.showsVerticalScrollIndicator=NO;self.categoryTable.rowHeight=64;self.categoryTable.dataSource=self;self.categoryTable.delegate=self;self.categoryTable.layer.borderWidth=2;self.categoryTable.layer.borderColor=[UIColor colorWithWhite:.20 alpha:1].CGColor;self.categoryTable.clipsToBounds=YES;UIView *categoryTopSpacer=[[[UIView alloc]initWithFrame:CGRectMake(0,0,1,24)]autorelease];categoryTopSpacer.backgroundColor=[UIColor clearColor];self.categoryTable.tableHeaderView=categoryTopSpacer;UIView *categoryBottomSpacer=[[[UIView alloc]initWithFrame:CGRectMake(0,0,1,24)]autorelease];categoryBottomSpacer.backgroundColor=[UIColor clearColor];self.categoryTable.tableFooterView=categoryBottomSpacer;[self.view addSubview:self.categoryTable];
    self.chartTable=[[[UITableView alloc]initWithFrame:CGRectZero style:UITableViewStylePlain]autorelease];self.chartTable.backgroundColor=[UIColor colorWithWhite:.14 alpha:1];self.chartTable.separatorColor=[UIColor colorWithWhite:.25 alpha:1];self.chartTable.rowHeight=64;self.chartTable.dataSource=self;self.chartTable.delegate=self;self.chartTable.hidden=YES;[self.view addSubview:self.chartTable];
    self.scrollView=[[[UIScrollView alloc]initWithFrame:CGRectZero]autorelease];self.scrollView.backgroundColor=[UIColor colorWithWhite:.92 alpha:1];self.scrollView.delegate=self;self.scrollView.minimumZoomScale=.01;self.scrollView.maximumZoomScale=5;self.scrollView.bouncesZoom=YES;[self.view addSubview:self.scrollView];
    self.imageView=[[[UIImageView alloc]initWithFrame:CGRectZero]autorelease];self.imageView.contentMode=UIViewContentModeScaleAspectFit;[self.scrollView addSubview:self.imageView];
    self.footer=[[[UIView alloc]initWithFrame:CGRectZero]autorelease];[self.view addSubview:self.footer];
    self.statusLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];self.statusLabel.backgroundColor=[UIColor clearColor];self.statusLabel.textColor=[UIColor whiteColor];self.statusLabel.font=[UIFont boldSystemFontOfSize:13];self.statusLabel.adjustsFontSizeToFitWidth=YES;self.statusLabel.minimumScaleFactor=.7;self.statusLabel.text=@"Enter an airport code or select downloaded content";[self.footer addSubview:self.statusLabel];
    NSUserDefaults *defaults=[NSUserDefaults standardUserDefaults];if(![defaults objectForKey:@"selectedICAO"]){NSDictionary *legacy=[defaults persistentDomainForName:@"com.skyning.atlassix"];for(NSString *key in [NSArray arrayWithObjects:@"selectedICAO",@"packAgentURL",nil])if([legacy objectForKey:key])[defaults setObject:[legacy objectForKey:key]forKey:key];}[self loadOfflinePacks];NSString *saved=[defaults stringForKey:@"selectedICAO"]?:@"KJFK";[self selectAirportByCode:saved];
}

- (void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated];[self loadOfflinePacks]; }
- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];CGSize size=self.view.bounds.size;CGFloat top=58,footer=34,rail=size.width<800?66:78,list=self.chartListVisible?MIN(300,MAX(240,size.width*.34)):0,contentHeight=size.height-top-footer;
    self.categoryRail.frame=CGRectMake(0,0,rail,size.height);self.topBar.frame=CGRectMake(rail,0,size.width-rail,top);self.footer.frame=CGRectMake(rail,size.height-footer,size.width-rail,footer);
    self.airportButton.frame=CGRectMake(7,12,rail-14,68);self.airportCaptionLabel.frame=CGRectMake(1,8,self.airportButton.bounds.size.width-2,13);CGFloat categoryPadding=48,categoryHeight=MIN(390,size.height-190),categoryTop=MAX(100,(size.height-categoryHeight)/2);self.categoryTable.frame=CGRectMake(6,categoryTop,rail-12,categoryHeight);self.categoryTable.layer.cornerRadius=self.categoryTable.bounds.size.width/2;
    NSUInteger categoryCount=MAX((NSUInteger)1,self.categories.count);self.categoryTable.rowHeight=(categoryHeight-categoryPadding)/categoryCount;if(!CGSizeEqualToSize(self.lastCategoryLayoutSize,size)){self.lastCategoryLayoutSize=size;[self.categoryTable reloadData];[self.categoryTable layoutIfNeeded];self.categoryTable.contentOffset=CGPointZero;}
    self.chartTable.frame=CGRectMake(rail,top,list,contentHeight);self.chartTable.hidden=!self.chartListVisible;self.scrollView.frame=CGRectMake(rail+list,top,size.width-rail-list,contentHeight);
    self.settingsButton.frame=CGRectMake(self.topBar.bounds.size.width-54,8,46,42);self.mapButton.frame=CGRectMake(self.topBar.bounds.size.width-106,8,46,42);self.weatherButton.frame=CGRectMake(7,size.height-footer-72,rail-14,58);self.titleLabel.frame=CGRectMake(12,5,self.topBar.bounds.size.width-132,46);self.statusLabel.frame=CGRectMake(8,1,self.footer.bounds.size.width-16,footer-2);
    [self styleAirportButton];[self styleChromeButton:self.settingsButton];[self styleChromeButton:self.mapButton];[self styleRailButton:self.weatherButton];
    if(self.topBar.layer.sublayers.count&&[[self.topBar.layer.sublayers objectAtIndex:0]isKindOfClass:[CAGradientLayer class]])[[self.topBar.layer.sublayers objectAtIndex:0]removeFromSuperlayer];[self.topBar.layer insertSublayer:[self gradient:self.topBar.bounds top:.38 bottom:.11]atIndex:0];if(self.footer.layer.sublayers.count&&[[self.footer.layer.sublayers objectAtIndex:0]isKindOfClass:[CAGradientLayer class]])[[self.footer.layer.sublayers objectAtIndex:0]removeFromSuperlayer];[self.footer.layer insertSublayer:[self gradient:self.footer.bounds top:.27 bottom:.07]atIndex:0];
    CGSize viewerSize=self.scrollView.bounds.size;if(!CGSizeEqualToSize(self.lastViewerSize,viewerSize)){self.lastViewerSize=viewerSize;if(self.imageView.image)[self performSelector:@selector(fitChart) withObject:nil afterDelay:0];}
}

- (NSString *)chartPackRoot { NSFileManager *fm=[NSFileManager defaultManager];NSString *root=@"/var/mobile/Library/SkyCharts/ChartPacks",*legacy=@"/var/mobile/Library/AtlasSix/ChartPacks";[fm createDirectoryAtPath:root withIntermediateDirectories:YES attributes:nil error:NULL];for(NSString *directory in [fm contentsOfDirectoryAtPath:legacy error:NULL]){NSString *source=[legacy stringByAppendingPathComponent:directory],*target=[root stringByAppendingPathComponent:directory];if(![fm fileExistsAtPath:target])[fm moveItemAtPath:source toPath:target error:NULL];}return root; }
- (void)loadOfflinePacks { NSString *root=[self chartPackRoot];NSMutableArray *values=[NSMutableArray array];for(NSString *directory in [[NSFileManager defaultManager]contentsOfDirectoryAtPath:root error:NULL]){NSString *packPath=[root stringByAppendingPathComponent:directory];NSData *data=[NSData dataWithContentsOfFile:[packPath stringByAppendingPathComponent:@"pack.json"]];NSDictionary *manifest=data?[NSJSONSerialization JSONObjectWithData:data options:0 error:NULL]:nil;for(NSDictionary *airport in [manifest objectForKey:@"airports"]){NSMutableDictionary *entry=[NSMutableDictionary dictionaryWithDictionary:airport];[entry setObject:packPath forKey:@"packPath"];[entry setObject:[manifest objectForKey:@"country"]?:@"Custom" forKey:@"packCountry"];[entry setObject:[manifest objectForKey:@"name"]?:directory forKey:@"packName"];[values addObject:entry];}}self.allAirports=values;if(!self.selectedAirport){self.airports=values;[self.airportTable reloadData];} }
- (void)promptAirportCode { UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:@"Select Airport" message:@"Enter a downloaded four-character ICAO code" delegate:self cancelButtonTitle:@"Cancel" otherButtonTitles:@"Select",nil]autorelease];alert.tag=200;alert.alertViewStyle=UIAlertViewStylePlainTextInput;UITextField *field=[alert textFieldAtIndex:0];field.autocapitalizationType=UITextAutocapitalizationTypeAllCharacters;field.text=[self.selectedAirport objectForKey:@"ident"]?:@"";[alert show]; }
- (NSArray *)LIDOCategoriesFromCategories:(NSArray *)rawCategories { NSArray *names=[NSArray arrayWithObjects:@"STAR",@"SID",@"APP",@"TAXI",@"MISC",nil],*airportTypes=[NSArray arrayWithObjects:@"AGC",@"APC",@"AFC",@"LVC",@"ADC",@"APT",nil];NSMutableArray *buckets=[NSMutableArray array];for(NSUInteger index=0;index<names.count;index++)[buckets addObject:[NSMutableArray array]];for(NSDictionary *source in rawCategories)for(NSDictionary *chart in [source objectForKey:@"charts"]){id rawType=[chart objectForKey:@"type"]?:[source objectForKey:@"name"]?:@"";NSString *type=[[rawType description]uppercaseString];NSUInteger bucket=4;if([type hasPrefix:@"STAR"]||[type hasPrefix:@"ARR"])bucket=0;else if([type hasPrefix:@"SID"]||[type hasPrefix:@"DEP"])bucket=1;else if([type isEqualToString:@"IAC"]||[type hasPrefix:@"APPROACH"])bucket=2;else if([airportTypes containsObject:type])bucket=3;[[buckets objectAtIndex:bucket]addObject:chart];}NSMutableArray *result=[NSMutableArray array];for(NSUInteger index=0;index<names.count;index++)[result addObject:[NSDictionary dictionaryWithObjectsAndKeys:[names objectAtIndex:index],@"name",[buckets objectAtIndex:index],@"charts",nil]];return result; }
- (void)rebuildChartGroups { if(self.selectedCategoryIndex<0||self.selectedCategoryIndex>=self.categories.count){self.chartGroups=[NSArray array];return;}NSArray *charts=[[self.categories objectAtIndex:self.selectedCategoryIndex]objectForKey:@"charts"]?:[NSArray array];NSMutableDictionary *byRunway=[NSMutableDictionary dictionary];for(NSDictionary *chart in charts){NSArray *runways=[chart objectForKey:@"runways"];if(!runways.count)runways=[NSArray arrayWithObject:@"GENERAL"];for(NSString *runwayValue in runways){NSString *runway=[[runwayValue description]stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];if(!runway.length)runway=@"GENERAL";NSString *key=[runway isEqualToString:@"GENERAL"]?@"GENERAL":[@"RWY " stringByAppendingString:[runway uppercaseString]];NSMutableArray *items=[byRunway objectForKey:key];if(!items){items=[NSMutableArray array];[byRunway setObject:items forKey:key];}if(![items containsObject:chart])[items addObject:chart];}}NSMutableArray *keys=[NSMutableArray arrayWithArray:[byRunway allKeys]];[keys sortUsingComparator:^NSComparisonResult(NSString *left,NSString *right){if([left isEqualToString:@"GENERAL"])return NSOrderedAscending;if([right isEqualToString:@"GENERAL"])return NSOrderedDescending;return [left compare:right options:NSNumericSearch];}];NSMutableArray *groups=[NSMutableArray array];for(NSString *key in keys)[groups addObject:[NSDictionary dictionaryWithObjectsAndKeys:key,@"name",[byRunway objectForKey:key],@"charts",nil]];self.chartGroups=groups; }
- (void)selectAirportByCode:(NSString *)code { [self loadOfflinePacks];NSString *target=[[code stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]uppercaseString];NSDictionary *match=nil;for(NSDictionary *airport in self.allAirports)if([[[airport objectForKey:@"ident"]uppercaseString]isEqual:target]){match=airport;break;}if(!match){[self.airportButton setTitle:target.length?target:@"----" forState:UIControlStateNormal];self.statusLabel.text=[NSString stringWithFormat:@"%@ is not installed. Use ⚙ to download it.",target];return;}self.selectedAirport=match;self.categories=[self LIDOCategoriesFromCategories:[match objectForKey:@"categories"]?:[NSArray array]];self.selectedCategoryIndex=0;self.selectedChart=nil;self.chartPages=nil;self.chartListVisible=YES;[self rebuildChartGroups];[[NSUserDefaults standardUserDefaults]setObject:target forKey:@"selectedICAO"];[self.airportButton setTitle:target forState:UIControlStateNormal];self.titleLabel.text=[match objectForKey:@"name"]?:target;[self.categoryTable reloadData];[self.chartTable reloadData];self.statusLabel.text=[NSString stringWithFormat:@"%@ • %@ • %@",[match objectForKey:@"packCountry"]?:@"",[match objectForKey:@"region"]?:@"",[match objectForKey:@"city"]?:@""];[self.view setNeedsLayout]; }
- (void)searchAirports { [self.searchField resignFirstResponder];[self loadOfflinePacks];NSString *needle=[[self.searchField.text stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]uppercaseString];NSMutableArray *matches=[NSMutableArray array];for(NSDictionary *airport in self.allAirports){NSString *haystack=[NSString stringWithFormat:@"%@ %@ %@ %@",[airport objectForKey:@"ident"]?:@"",[airport objectForKey:@"name"]?:@"",[airport objectForKey:@"city"]?:@"",[airport objectForKey:@"region"]?:@""];if([[haystack uppercaseString]rangeOfString:needle].location!=NSNotFound)[matches addObject:airport];}self.airports=matches;self.airportTable.hidden=NO;self.chartTable.hidden=YES;[self.airportTable reloadData];self.statusLabel.text=[NSString stringWithFormat:@"%lu downloaded airports found",(unsigned long)matches.count]; }
- (BOOL)textFieldShouldReturn:(UITextField *)field { [self searchAirports];return YES; }

- (NSInteger)numberOfSectionsInTableView:(UITableView *)table { return table==self.chartTable?self.chartGroups.count:1; }
- (NSInteger)tableView:(UITableView *)table numberOfRowsInSection:(NSInteger)section { if(table==self.categoryTable)return self.categories.count;if(section<0||section>=self.chartGroups.count)return 0;return [[[self.chartGroups objectAtIndex:section]objectForKey:@"charts"]count]; }
- (CGFloat)tableView:(UITableView *)table heightForHeaderInSection:(NSInteger)section { return table==self.chartTable?28:0; }
- (UIView *)tableView:(UITableView *)table viewForHeaderInSection:(NSInteger)section { if(table!=self.chartTable)return nil;UIView *header=[[[UIView alloc]initWithFrame:CGRectMake(0,0,table.bounds.size.width,28)]autorelease];header.backgroundColor=[UIColor colorWithWhite:.105 alpha:1];UILabel *label=[[[UILabel alloc]initWithFrame:CGRectMake(8,0,table.bounds.size.width-16,28)]autorelease];label.backgroundColor=[UIColor clearColor];label.textColor=[UIColor whiteColor];label.shadowColor=[UIColor blackColor];label.shadowOffset=CGSizeMake(0,-1);label.font=[UIFont boldSystemFontOfSize:15];label.text=[[self.chartGroups objectAtIndex:section]objectForKey:@"name"];[header addSubview:label];return header; }
- (UIColor *)stripeColorForChartType:(NSString *)value { id raw=value?:@"";NSString *type=[[raw description]uppercaseString];if([type isEqual:@"SIDPT"]||[type isEqual:@"STARPT"])return [UIColor colorWithWhite:.78 alpha:1];if([type hasPrefix:@"SID"])return [UIColor colorWithRed:.35 green:.72 blue:.35 alpha:1];if([type hasPrefix:@"STAR"])return [UIColor colorWithRed:1 green:.63 blue:.28 alpha:1];if([type isEqual:@"IAC"]||[type hasPrefix:@"APP"])return [UIColor colorWithRed:.29 green:.70 blue:.82 alpha:1];if([type isEqual:@"AFC"])return [UIColor colorWithRed:.68 green:.42 blue:.59 alpha:1];if([type isEqual:@"AGC"]||[type isEqual:@"APC"])return [UIColor colorWithRed:1 green:.65 blue:.52 alpha:1];if([type isEqual:@"LVC"])return [UIColor colorWithRed:.42 green:.66 blue:.83 alpha:1];if([type isEqual:@"MRC"])return [UIColor colorWithRed:.58 green:.80 blue:.86 alpha:1];if([type isEqual:@"AOI"])return [UIColor colorWithWhite:.78 alpha:1];if([type isEqual:@"ADC"]||[type isEqual:@"APT"])return [UIColor colorWithRed:.84 green:.70 blue:.39 alpha:1];return [UIColor colorWithWhite:.68 alpha:1]; }
- (UITableViewCell *)tableView:(UITableView *)table cellForRowAtIndexPath:(NSIndexPath *)path {
    if(table==self.categoryTable){
        UITableViewCell *cell=[table dequeueReusableCellWithIdentifier:@"category"];
        UILabel *plainLabel,*selectedLabel;UIView *selector,*inner;
        if(!cell){
            cell=[[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"category"]autorelease];cell.selectionStyle=UITableViewCellSelectionStyleNone;cell.backgroundColor=[UIColor clearColor];
            plainLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];plainLabel.tag=201;plainLabel.backgroundColor=[UIColor clearColor];plainLabel.textColor=[UIColor whiteColor];plainLabel.textAlignment=NSTextAlignmentCenter;plainLabel.font=[UIFont boldSystemFontOfSize:14];plainLabel.shadowColor=[UIColor blackColor];plainLabel.shadowOffset=CGSizeMake(0,-1);[cell.contentView addSubview:plainLabel];
            selector=[[[UIView alloc]initWithFrame:CGRectZero]autorelease];selector.tag=202;selector.layer.cornerRadius=7;selector.layer.borderWidth=1;selector.layer.borderColor=[UIColor colorWithRed:.35 green:.02 blue:0 alpha:1].CGColor;selector.clipsToBounds=YES;[cell.contentView addSubview:selector];
            inner=[[[UIView alloc]initWithFrame:CGRectZero]autorelease];inner.tag=203;inner.backgroundColor=[UIColor colorWithWhite:.13 alpha:1];inner.layer.cornerRadius=5;inner.layer.borderWidth=2;inner.layer.borderColor=[UIColor colorWithWhite:.04 alpha:1].CGColor;[selector addSubview:inner];
            selectedLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];selectedLabel.tag=204;selectedLabel.backgroundColor=[UIColor clearColor];selectedLabel.textColor=[UIColor whiteColor];selectedLabel.textAlignment=NSTextAlignmentCenter;selectedLabel.font=[UIFont boldSystemFontOfSize:14];selectedLabel.shadowColor=[UIColor blackColor];selectedLabel.shadowOffset=CGSizeMake(0,-1);[inner addSubview:selectedLabel];
        }else{plainLabel=(UILabel *)[cell.contentView viewWithTag:201];selector=[cell.contentView viewWithTag:202];inner=[selector viewWithTag:203];selectedLabel=(UILabel *)[inner viewWithTag:204];}
        NSDictionary *category=[self.categories objectAtIndex:path.row];BOOL selected=path.row==self.selectedCategoryIndex;
        NSString *title=[[category objectForKey:@"name"]uppercaseString];CGFloat width=table.bounds.size.width,height=table.rowHeight;plainLabel.frame=CGRectMake(0,0,width,height);plainLabel.text=title;plainLabel.hidden=selected;selector.frame=CGRectMake(1,2,width-2,height-4);selector.hidden=!selected;inner.frame=CGRectMake(6,9,selector.bounds.size.width-12,selector.bounds.size.height-18);selectedLabel.frame=inner.bounds;selectedLabel.text=title;
        if(selected){if(selector.layer.sublayers.count&&[[selector.layer.sublayers objectAtIndex:0]isKindOfClass:[CAGradientLayer class]])[[selector.layer.sublayers objectAtIndex:0]removeFromSuperlayer];CAGradientLayer *orange=[self selectionGradient:selector.bounds];orange.cornerRadius=7;[selector.layer insertSublayer:orange atIndex:0];}
        return cell;
    }
    UITableViewCell *cell=[table dequeueReusableCellWithIdentifier:@"chartCustom"];UILabel *nameLabel,*detailLabel,*typeLabel;UIView *typeStripe;
    if(!cell){
        cell=[[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"chartCustom"]autorelease];
        typeStripe=[[[UIView alloc]initWithFrame:CGRectZero]autorelease];typeStripe.tag=103;typeStripe.userInteractionEnabled=NO;typeStripe.layer.borderWidth=1;typeStripe.layer.borderColor=[UIColor colorWithWhite:.08 alpha:1].CGColor;[cell.contentView addSubview:typeStripe];
        typeLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];typeLabel.tag=104;typeLabel.backgroundColor=[UIColor clearColor];typeLabel.textColor=[UIColor blackColor];typeLabel.textAlignment=NSTextAlignmentCenter;typeLabel.font=[UIFont boldSystemFontOfSize:11];typeLabel.adjustsFontSizeToFitWidth=YES;typeLabel.minimumScaleFactor=.72;[typeStripe addSubview:typeLabel];
        nameLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];nameLabel.tag=101;nameLabel.backgroundColor=[UIColor clearColor];nameLabel.textColor=[UIColor whiteColor];nameLabel.font=[UIFont boldSystemFontOfSize:15];nameLabel.numberOfLines=2;nameLabel.lineBreakMode=NSLineBreakByTruncatingTail;[cell.contentView addSubview:nameLabel];
        detailLabel=[[[UILabel alloc]initWithFrame:CGRectZero]autorelease];detailLabel.tag=102;detailLabel.backgroundColor=[UIColor clearColor];detailLabel.textColor=[UIColor lightGrayColor];detailLabel.font=[UIFont systemFontOfSize:11];detailLabel.numberOfLines=1;detailLabel.lineBreakMode=NSLineBreakByTruncatingTail;[cell.contentView addSubview:detailLabel];
    }else{nameLabel=(UILabel *)[cell.contentView viewWithTag:101];detailLabel=(UILabel *)[cell.contentView viewWithTag:102];typeStripe=[cell.contentView viewWithTag:103];typeLabel=(UILabel *)[typeStripe viewWithTag:104];}
    CGFloat stripeWidth=38,rowHeight=table.rowHeight,textX=stripeWidth+8,width=MAX(100,table.bounds.size.width-textX-42);typeStripe.frame=CGRectMake(0,0,stripeWidth,rowHeight-1);typeLabel.transform=CGAffineTransformIdentity;typeLabel.bounds=CGRectMake(0,0,rowHeight-7,stripeWidth-2);typeLabel.center=CGPointMake(typeStripe.bounds.size.width/2,typeStripe.bounds.size.height/2);typeLabel.transform=CGAffineTransformMakeRotation(-1.57079632679);nameLabel.frame=CGRectMake(textX,5,width,37);detailLabel.frame=CGRectMake(textX,43,width,16);
    NSDictionary *chart=[[[self.chartGroups objectAtIndex:path.section]objectForKey:@"charts"]objectAtIndex:path.row];id rawType=[chart objectForKey:@"type"]?:@"CHART";NSString *chartType=[[rawType description]uppercaseString];typeStripe.backgroundColor=[self stripeColorForChartType:chartType];typeLabel.text=chartType;nameLabel.attributedText=nil;nameLabel.text=[chart objectForKey:@"name"]?:@"";NSArray *runways=[chart objectForKey:@"runways"];detailLabel.text=runways.count?[runways componentsJoinedByString:@", "]:chartType;
    cell.backgroundColor=chart==self.selectedChart?[UIColor colorWithRed:.10 green:.42 blue:.68 alpha:1]:[UIColor colorWithWhite:.17 alpha:1];cell.accessoryType=chart==self.selectedChart?UITableViewCellAccessoryCheckmark:UITableViewCellAccessoryNone;return cell;
}
- (void)transitionChartListVisible:(BOOL)shown {
    CGSize size=self.view.bounds.size;CGFloat top=58,footer=34,rail=size.width<800?66:78,list=MIN(300,MAX(240,size.width*.34)),contentHeight=size.height-top-footer;
    CGFloat viewerX=rail+(shown?list:0),viewerWidth=size.width-rail-(shown?list:0);
    self.chartListVisible=shown;self.chartTable.hidden=NO;self.chartTable.frame=CGRectMake(shown?rail-list:rail,top,list,contentHeight);
    [self.view bringSubviewToFront:self.categoryRail];[self.view bringSubviewToFront:self.categoryTable];[self.view bringSubviewToFront:self.topBar];[self.view bringSubviewToFront:self.footer];
    self.chartTable.alpha=shown?0:1;
    [UIView beginAnimations:@"SkyChartsChartList" context:NULL];[UIView setAnimationDuration:.28];[UIView setAnimationCurve:UIViewAnimationCurveEaseInOut];[UIView setAnimationBeginsFromCurrentState:YES];[UIView setAnimationDelegate:self];[UIView setAnimationDidStopSelector:@selector(chartListTransitionDidStop:finished:context:)];
    self.chartTable.alpha=shown?1:0;self.chartTable.frame=CGRectMake(shown?rail:rail-list,top,list,contentHeight);self.scrollView.frame=CGRectMake(viewerX,top,viewerWidth,contentHeight);[UIView commitAnimations];
}
- (void)chartListTransitionDidStop:(NSString *)animationID finished:(NSNumber *)finished context:(void *)context { self.chartTable.hidden=!self.chartListVisible;self.chartTable.alpha=1;[self.view setNeedsLayout];[self.view layoutIfNeeded];if(self.imageView.image)[self fitChart]; }
- (void)tableView:(UITableView *)table didSelectRowAtIndexPath:(NSIndexPath *)path {
    if(table==self.categoryTable){
        BOOL shouldShow=!(path.row==self.selectedCategoryIndex&&self.chartListVisible),visibilityChanged=shouldShow!=self.chartListVisible;
        if(path.row!=self.selectedCategoryIndex){self.selectedCategoryIndex=path.row;self.selectedChart=nil;[self rebuildChartGroups];}
        [self.categoryTable reloadData];[self.chartTable reloadData];
        if(visibilityChanged)[self transitionChartListVisible:shouldShow];else if(self.imageView.image)[self fitChart];
    }else{self.selectedChart=[[[self.chartGroups objectAtIndex:path.section]objectForKey:@"charts"]objectAtIndex:path.row];self.chartPages=[self.selectedChart objectForKey:@"pages"]?:[NSArray array];self.pageIndex=0;[self.chartTable reloadData];[self loadCurrentImage];}
}

- (void)loadCurrentImage { if(!self.chartPages.count)return;NSDictionary *page=[self.chartPages objectAtIndex:self.pageIndex];NSString *relative=[page objectForKey:@"light"];NSString *path=[[self.selectedAirport objectForKey:@"packPath"]stringByAppendingPathComponent:relative];[self performSelectorInBackground:@selector(loadImageBackground:)withObject:path];self.statusLabel.text=@"Loading offline chart…"; }
- (void)loadImageBackground:(NSString *)path { NSAutoreleasePool *pool=[[NSAutoreleasePool alloc]init];UIImage *image=[UIImage imageWithContentsOfFile:path];[self performSelectorOnMainThread:@selector(imageFinished:)withObject:image waitUntilDone:NO];[pool drain]; }
- (void)imageFinished:(UIImage *)image { if(!image){self.statusLabel.text=@"Offline chart image is missing";return;}[self.view layoutIfNeeded];self.scrollView.contentInset=UIEdgeInsetsZero;self.scrollView.minimumZoomScale=.01;self.scrollView.maximumZoomScale=5;self.scrollView.zoomScale=1;self.imageView.transform=CGAffineTransformIdentity;self.imageView.image=image;self.imageView.frame=CGRectMake(0,0,image.size.width,image.size.height);self.scrollView.contentSize=image.size;[self fitChart];[self performSelector:@selector(centerChart) withObject:nil afterDelay:0];self.titleLabel.text=[self.selectedChart objectForKey:@"name"];self.statusLabel.text=[NSString stringWithFormat:@"%@ • %@ • page %ld/%lu",[self.selectedAirport objectForKey:@"ident"],[self.selectedChart objectForKey:@"type"],(long)self.pageIndex+1,(unsigned long)self.chartPages.count]; }
- (UIView *)viewForZoomingInScrollView:(UIScrollView *)scroll { return self.imageView; }
- (void)centerChart { CGSize bounds=self.scrollView.bounds.size,content=self.scrollView.contentSize;self.scrollView.contentInset=UIEdgeInsetsZero;self.imageView.center=CGPointMake(MAX(content.width,bounds.width)/2,MAX(content.height,bounds.height)/2); }
- (void)scrollViewDidZoom:(UIScrollView *)scrollView { if(scrollView==self.scrollView)[self centerChart]; }
- (void)fitChart { if(!self.imageView.image)return;[self.scrollView layoutIfNeeded];CGSize bounds=self.scrollView.bounds.size,image=self.imageView.image.size;if(bounds.width<=0||bounds.height<=0)return;CGFloat scale=MIN(bounds.width/image.width,bounds.height/image.height);self.scrollView.contentInset=UIEdgeInsetsZero;self.scrollView.minimumZoomScale=.01;self.scrollView.maximumZoomScale=MAX(5,scale);self.scrollView.zoomScale=scale;self.scrollView.minimumZoomScale=scale;[self centerChart];CGFloat x=MAX(0,(self.scrollView.contentSize.width-bounds.width)/2),y=MAX(0,(self.scrollView.contentSize.height-bounds.height)/2);self.scrollView.contentOffset=CGPointMake(x,y);[self performSelector:@selector(centerChart) withObject:nil afterDelay:0]; }
- (void)previousPage { if(self.pageIndex>0){self.pageIndex--;[self loadCurrentImage];} }
- (void)nextPage { if(self.pageIndex+1<self.chartPages.count){self.pageIndex++;[self loadCurrentImage];} }

- (void)showWeather { NSString *icao=[self.selectedAirport objectForKey:@"ident"];if(!icao.length){UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:@"Weather" message:@"Select an installed airport before requesting METAR weather." delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil]autorelease];[alert show];return;}WeatherViewController *weather=[[[WeatherViewController alloc]initWithICAO:icao]autorelease];UINavigationController *nav=[[[UINavigationController alloc]initWithRootViewController:weather]autorelease];nav.modalPresentationStyle=UIModalPresentationFormSheet;[self presentModalViewController:nav animated:YES]; }
- (NSString *)airportMapRoot { NSString *root=@"/var/mobile/Library/SkyCharts/AirportMaps";[[NSFileManager defaultManager]createDirectoryAtPath:root withIntermediateDirectories:YES attributes:nil error:NULL];return root; }
- (NSString *)airportMapPathForICAO:(NSString *)icao { return [[self airportMapRoot]stringByAppendingPathComponent:[NSString stringWithFormat:@"%@.json",[icao uppercaseString]]]; }
- (NSString *)installedAirportMapPath { NSString *relative=[self.selectedAirport objectForKey:@"map"],*packPath=[self.selectedAirport objectForKey:@"packPath"];if(relative.length&&packPath.length&&![relative hasPrefix:@"/"]&&[relative rangeOfString:@".."].location==NSNotFound){NSString *bundled=[packPath stringByAppendingPathComponent:relative];if([[NSFileManager defaultManager]fileExistsAtPath:bundled])return bundled;}NSString *icao=[self.selectedAirport objectForKey:@"ident"],*legacy=[self airportMapPathForICAO:icao];return [[NSFileManager defaultManager]fileExistsAtPath:legacy]?legacy:nil; }
- (void)openAirportMap { NSString *icao=[self.selectedAirport objectForKey:@"ident"];if(!icao.length){UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:@"Airport Map" message:@"Select an installed airport before opening its map." delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil]autorelease];[alert show];return;}NSString *path=[self installedAirportMapPath];if(!path){UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:[NSString stringWithFormat:@"%@ Airport Map",icao]message:@"This chart package does not contain an interactive airport map. Re-download the airport while the Mac Pack Agent is running."delegate:nil cancelButtonTitle:@"OK"otherButtonTitles:nil]autorelease];[alert show];return;}AirportMapViewController *map=[[[AirportMapViewController alloc]initWithICAO:icao mapPath:path]autorelease];UINavigationController *nav=[[[UINavigationController alloc]initWithRootViewController:map]autorelease];nav.modalPresentationStyle=UIModalPresentationFullScreen;[self presentModalViewController:nav animated:YES]; }
- (NSString *)agentBase { return [[NSUserDefaults standardUserDefaults]stringForKey:@"packAgentURL"]?:@"http://192.168.2.2:8770"; }
- (void)openPackMenu { UIActionSheet *sheet=[[[UIActionSheet alloc]initWithTitle:@"Settings" delegate:self cancelButtonTitle:@"Cancel" destructiveButtonTitle:nil otherButtonTitles:@"Download by Country",@"Download by ICAO Code",@"Manage Downloaded Content",@"About SkyCharts",nil]autorelease];[sheet showInView:self.view]; }
- (void)actionSheet:(UIActionSheet *)sheet clickedButtonAtIndex:(NSInteger)index { if(index==0)[self showAgentPromptForMode:101];else if(index==1)[self showAgentPromptForMode:102];else if(index==2){ContentManagerViewController *manager=[[[ContentManagerViewController alloc]init]autorelease];UINavigationController *nav=[[[UINavigationController alloc]initWithRootViewController:manager]autorelease];nav.modalPresentationStyle=UIModalPresentationFormSheet;[self presentModalViewController:nav animated:YES];}else if(index==3){AboutViewController *about=[[[AboutViewController alloc]init]autorelease];UINavigationController *nav=[[[UINavigationController alloc]initWithRootViewController:about]autorelease];nav.modalPresentationStyle=UIModalPresentationFormSheet;[self presentModalViewController:nav animated:YES];} }
- (void)showAgentPromptForMode:(NSInteger)mode { UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:@"Mac Pack Agent" message:@"Enter the Mac agent address" delegate:self cancelButtonTitle:@"Cancel" otherButtonTitles:@"Next",nil]autorelease];alert.tag=mode==101?110:120;alert.alertViewStyle=UIAlertViewStylePlainTextInput;[alert textFieldAtIndex:0].text=[self agentBase];[alert show]; }
- (void)showCountryPrompt { UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:@"Download Country" message:@"Two-letter code, e.g. CA. Use CA:10 for a trial." delegate:self cancelButtonTitle:@"Cancel" otherButtonTitles:@"Download",nil]autorelease];alert.tag=101;alert.alertViewStyle=UIAlertViewStylePlainTextInput;[alert show]; }
- (void)showICAOPackPrompt { UIAlertView *alert=[[[UIAlertView alloc]initWithTitle:@"Download Airports" message:@"Enter ICAO codes separated by commas" delegate:self cancelButtonTitle:@"Cancel" otherButtonTitles:@"Download",nil]autorelease];alert.tag=102;alert.alertViewStyle=UIAlertViewStylePlainTextInput;[alert show]; }
- (void)alertView:(UIAlertView *)alert clickedButtonAtIndex:(NSInteger)index { if(index!=1)return;if(alert.tag==110||alert.tag==120){NSString *url=[[alert textFieldAtIndex:0].text stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];while([url hasSuffix:@"/"])url=[url substringToIndex:url.length-1];[[NSUserDefaults standardUserDefaults]setObject:url forKey:@"packAgentURL"];if(alert.tag==110)[self showCountryPrompt];else[self showICAOPackPrompt];}else if(alert.tag==101)[self startPackJob:[[[alert textFieldAtIndex:0].text uppercaseString]stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]];else if(alert.tag==102)[self startAirportPackJob:[[[alert textFieldAtIndex:0].text uppercaseString]stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]]];else if(alert.tag==200)[self selectAirportByCode:[alert textFieldAtIndex:0].text]; }
- (void)requestJSON:(NSDictionary *)task { [self performSelectorInBackground:@selector(requestJSONBackground:)withObject:task]; }
- (void)requestJSONBackground:(NSDictionary *)task { NSAutoreleasePool *pool=[[NSAutoreleasePool alloc]init];NSData *data=[NSData dataWithContentsOfURL:[NSURL URLWithString:[task objectForKey:@"url"]]];id json=data?[NSJSONSerialization JSONObjectWithData:data options:0 error:NULL]:nil;NSDictionary *result=[NSDictionary dictionaryWithObjectsAndKeys:[task objectForKey:@"kind"],@"kind",json?:[NSNull null],@"json",nil];[self performSelectorOnMainThread:@selector(JSONFinished:)withObject:result waitUntilDone:NO];[pool drain]; }
- (void)startPackJob:(NSString *)request { self.packStartedAt=[NSDate timeIntervalSinceReferenceDate];NSArray *parts=[request componentsSeparatedByString:@":"];NSString *url=[NSString stringWithFormat:@"%@/api/build?country=%@",[self agentBase],[parts objectAtIndex:0]];if(parts.count>1)url=[url stringByAppendingFormat:@"&limit=%@",[parts objectAtIndex:1]];self.statusLabel.text=@"Requesting charts and airport maps from Mac…";[self requestJSON:[NSDictionary dictionaryWithObjectsAndKeys:@"start",@"kind",url,@"url",nil]]; }
- (void)startAirportPackJob:(NSString *)idents { self.packStartedAt=[NSDate timeIntervalSinceReferenceDate];NSString *encoded=[idents stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];NSString *url=[NSString stringWithFormat:@"%@/api/build-airports?idents=%@",[self agentBase],encoded];self.statusLabel.text=@"Requesting charts and airport maps from Mac…";[self requestJSON:[NSDictionary dictionaryWithObjectsAndKeys:@"start",@"kind",url,@"url",nil]]; }
- (void)pollPackJob { if(self.packJobID)[self requestJSON:[NSDictionary dictionaryWithObjectsAndKeys:@"poll",@"kind",[NSString stringWithFormat:@"%@/api/jobs/%@",[self agentBase],self.packJobID],@"url",nil]]; }
- (NSString *)remainingTextForSeconds:(NSInteger)seconds { if(seconds<45)return @"less than a minute remaining";NSInteger minutes=MAX(1,(seconds+30)/60);if(minutes<90)return [NSString stringWithFormat:@"about %ld min remaining",(long)minutes];NSInteger hours=minutes/60,remainder=minutes%60;if(remainder<10)return [NSString stringWithFormat:@"about %ld hr remaining",(long)hours];return [NSString stringWithFormat:@"about %ld hr %ld min remaining",(long)hours,(long)remainder]; }
- (NSString *)jobStatusText:(NSDictionary *)json fallback:(NSString *)fallback { NSString *base=[json objectForKey:@"progress"]?:fallback;if([base hasPrefix:@"@@SKYCHARTS_PROGRESS"])base=fallback;NSNumber *fraction=[json objectForKey:@"fraction"],*eta=[json objectForKey:@"etaSeconds"];double value=[fraction doubleValue];NSInteger etaValue=[eta integerValue];if(etaValue<=0&&value>.005&&value<1&&self.packStartedAt>0){NSTimeInterval elapsed=[NSDate timeIntervalSinceReferenceDate]-self.packStartedAt;if(elapsed>2)etaValue=(NSInteger)(elapsed*(1-value)/value);}NSMutableArray *parts=[NSMutableArray arrayWithObject:base];if(value>0&&value<1)[parts addObject:[NSString stringWithFormat:@"%ld%%",(long)(value*100+.5)]];if(etaValue>0)[parts addObject:[self remainingTextForSeconds:etaValue]];return [parts componentsJoinedByString:@" • "]; }
- (void)JSONFinished:(NSDictionary *)result { id json=[result objectForKey:@"json"];if(json==[NSNull null]){self.statusLabel.text=@"Could not contact Mac Pack Agent";return;}if([[result objectForKey:@"kind"]isEqual:@"start"]){self.packJobID=[json objectForKey:@"id"];if(!self.packJobID){self.statusLabel.text=[json objectForKey:@"error"]?:@"Mac refused the pack request";return;}self.statusLabel.text=[self jobStatusText:json fallback:@"Mac is building the pack…"];[self performSelector:@selector(pollPackJob)withObject:nil afterDelay:2];}else{NSString *status=[json objectForKey:@"status"];if([status isEqual:@"ready"]){self.statusLabel.text=[json objectForKey:@"archive"]?@"Pack ready; starting one-stream transfer…":@"Pack ready; using compatibility transfer…";if([json objectForKey:@"archive"])[self performSelectorInBackground:@selector(installPackArchiveBackground:)withObject:json];else[self performSelectorInBackground:@selector(installPackStreamingBackground:)withObject:[json objectForKey:@"manifest"]];}else if([status isEqual:@"failed"])self.statusLabel.text=[json objectForKey:@"error"]?:@"Pack build failed";else{self.statusLabel.text=[self jobStatusText:json fallback:@"Mac is still building the pack…"];[self performSelector:@selector(pollPackJob)withObject:nil afterDelay:2];}} }
- (void)installPackArchiveBackground:(NSDictionary *)job {
    NSAutoreleasePool *pool=[[NSAutoreleasePool alloc]init];NSString *path=[job objectForKey:@"archive"];NSURL *url=[NSURL URLWithString:[[self agentBase]stringByAppendingString:path]];PackArchiveInstaller *installer=[[PackArchiveInstaller alloc]initWithURL:url chartRoot:[self chartPackRoot] jobID:self.packJobID expectedBytes:[[job objectForKey:@"archiveBytes"]longLongValue] expectedFiles:[[job objectForKey:@"archiveFiles"]unsignedIntegerValue] progressTarget:self selector:@selector(packArchiveProgress:)];BOOL ok=[installer run];[installer release];[self performSelectorOnMainThread:ok?@selector(packFinished):@selector(packFailed)withObject:nil waitUntilDone:NO];[pool drain];
}
- (void)packArchiveProgress:(NSArray *)values { NSUInteger current=[[values objectAtIndex:0]unsignedIntegerValue],files=[[values objectAtIndex:1]unsignedIntegerValue];long long received=[[values objectAtIndex:2]longLongValue],total=[[values objectAtIndex:3]longLongValue];NSInteger eta=[[values objectAtIndex:4]integerValue],percent=total>0?(NSInteger)(received*100/total):0;NSString *fileText=files?[NSString stringWithFormat:@"%lu / %lu files",(unsigned long)MIN(current,files),(unsigned long)files]:[NSString stringWithFormat:@"%lu files",(unsigned long)current];NSString *status=[NSString stringWithFormat:@"Installing %@ • %ld%%",fileText,(long)MIN(100,percent)];if(eta>0)status=[status stringByAppendingFormat:@" • %@",[self remainingTextForSeconds:eta]];self.statusLabel.text=status; }
- (NSMutableArray *)assetsForPackManifest:(NSDictionary *)manifest { NSMutableArray *assets=[NSMutableArray array];for(NSDictionary *airport in [manifest objectForKey:@"airports"]){NSString *map=[airport objectForKey:@"map"];if(map.length)[assets addObject:map];for(NSDictionary *category in [airport objectForKey:@"categories"])for(NSDictionary *chart in [category objectForKey:@"charts"])for(NSDictionary *page in [chart objectForKey:@"pages"])if([page objectForKey:@"light"])[assets addObject:[page objectForKey:@"light"]];}return assets; }
- (void)installPackStreamingBackground:(NSString *)manifestPath {
    NSAutoreleasePool *pool=[[NSAutoreleasePool alloc]init];NSFileManager *fm=[NSFileManager defaultManager];
    NSData *manifestData=[[NSData alloc]initWithContentsOfURL:[NSURL URLWithString:[[self agentBase]stringByAppendingString:manifestPath]]];NSDictionary *manifest=manifestData?[NSJSONSerialization JSONObjectWithData:manifestData options:0 error:NULL]:nil;NSString *packID=[manifest objectForKey:@"packId"];
    BOOL ok=packID.length&&[packID rangeOfString:@"/"].location==NSNotFound&&[packID rangeOfString:@".."].location==NSNotFound;NSString *root=[self chartPackRoot],*incoming=[root stringByAppendingPathComponent:[@".incoming-"stringByAppendingString:packID?:@"invalid"]];
    [fm createDirectoryAtPath:root withIntermediateDirectories:YES attributes:nil error:NULL];[fm removeItemAtPath:incoming error:NULL];[fm createDirectoryAtPath:incoming withIntermediateDirectories:YES attributes:nil error:NULL];if(![fm fileExistsAtPath:incoming])ok=NO;
    NSMutableArray *assets=[self assetsForPackManifest:manifest];
    NSUInteger current=0,total=assets.count;CFAbsoluteTime started=CFAbsoluteTimeGetCurrent();NSString *prefix=[NSString stringWithFormat:@"%@/packs/%@/",[self agentBase],self.packJobID];
    for(NSString *asset in assets){
        NSAutoreleasePool *filePool=[[NSAutoreleasePool alloc]init];if(!ok||[asset rangeOfString:@".."].location!=NSNotFound){ok=NO;[filePool drain];break;}
        NSString *urlText=[[prefix stringByAppendingString:asset]stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding],*target=[incoming stringByAppendingPathComponent:asset];[fm createDirectoryAtPath:[target stringByDeletingLastPathComponent]withIntermediateDirectories:YES attributes:nil error:NULL];
        NSData *data=[[NSData alloc]initWithContentsOfURL:[NSURL URLWithString:urlText]];ok=data&&[data writeToFile:target atomically:YES];[data release];if(!ok){[filePool drain];break;}current++;
        if(current==1||current%2==0||current==total){NSTimeInterval elapsed=CFAbsoluteTimeGetCurrent()-started;NSInteger eta=current&&elapsed>2?(NSInteger)(elapsed*(total-current)/current):0;NSArray *values=[NSArray arrayWithObjects:[NSNumber numberWithUnsignedInteger:current],[NSNumber numberWithUnsignedInteger:total],[NSNumber numberWithInteger:eta],nil];[self performSelectorOnMainThread:@selector(packProgress:)withObject:values waitUntilDone:YES];}
        [filePool drain];
    }
    if(ok)ok=[manifestData writeToFile:[incoming stringByAppendingPathComponent:@"pack.json"]atomically:YES];[manifestData release];if(ok){NSString *target=[root stringByAppendingPathComponent:packID];[fm removeItemAtPath:target error:NULL];ok=[fm moveItemAtPath:incoming toPath:target error:NULL];}if(!ok)[fm removeItemAtPath:incoming error:NULL];[self performSelectorOnMainThread:ok?@selector(packFinished):@selector(packFailed)withObject:nil waitUntilDone:NO];[pool drain];
}
- (void)installPackBackground:(NSString *)manifestPath { NSAutoreleasePool *pool=[[NSAutoreleasePool alloc]init];NSData *manifestData=[NSData dataWithContentsOfURL:[NSURL URLWithString:[[self agentBase]stringByAppendingString:manifestPath]]];NSDictionary *manifest=manifestData?[NSJSONSerialization JSONObjectWithData:manifestData options:0 error:NULL]:nil;NSString *packID=[manifest objectForKey:@"packId"];BOOL ok=packID.length&&[packID rangeOfString:@"/"].location==NSNotFound&&[packID rangeOfString:@".."].location==NSNotFound;NSString *root=[self chartPackRoot],*incoming=[root stringByAppendingPathComponent:[@".incoming-"stringByAppendingString:packID?:@"invalid"]];NSFileManager *fm=[NSFileManager defaultManager];[fm createDirectoryAtPath:root withIntermediateDirectories:YES attributes:nil error:NULL];[fm removeItemAtPath:incoming error:NULL];[fm createDirectoryAtPath:incoming withIntermediateDirectories:YES attributes:nil error:NULL];if(![fm fileExistsAtPath:incoming])ok=NO;NSMutableArray *assets=[self assetsForPackManifest:manifest];NSUInteger current=0;NSString *prefix=[NSString stringWithFormat:@"%@/packs/%@/",[self agentBase],self.packJobID];for(NSString *asset in assets){if(!ok||[asset rangeOfString:@".."].location!=NSNotFound){ok=NO;break;}NSData *data=[NSData dataWithContentsOfURL:[NSURL URLWithString:[[prefix stringByAppendingString:asset]stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]]];NSString *target=[incoming stringByAppendingPathComponent:asset];[fm createDirectoryAtPath:[target stringByDeletingLastPathComponent]withIntermediateDirectories:YES attributes:nil error:NULL];ok=data&&[data writeToFile:target atomically:YES];if(!ok)break;current++;if(current%5==0||current==assets.count)[self performSelectorOnMainThread:@selector(packProgress:)withObject:[NSArray arrayWithObjects:[NSNumber numberWithUnsignedInteger:current],[NSNumber numberWithUnsignedInteger:assets.count],nil]waitUntilDone:NO];}if(ok)ok=[manifestData writeToFile:[incoming stringByAppendingPathComponent:@"pack.json"]atomically:YES];if(ok){NSString *target=[root stringByAppendingPathComponent:packID];[fm removeItemAtPath:target error:NULL];ok=[fm moveItemAtPath:incoming toPath:target error:NULL];}if(!ok)[fm removeItemAtPath:incoming error:NULL];[self performSelectorOnMainThread:ok?@selector(packFinished):@selector(packFailed)withObject:nil waitUntilDone:NO];[pool drain]; }
- (void)packProgress:(NSArray *)values { NSInteger current=[[values objectAtIndex:0]integerValue],total=[[values objectAtIndex:1]integerValue],eta=values.count>2?[[values objectAtIndex:2]integerValue]:0,percent=total?(current*100/total):100;NSString *status=[NSString stringWithFormat:@"Installing %ld / %ld files • %ld%%",(long)current,(long)total,(long)percent];if(eta>0)status=[status stringByAppendingFormat:@" • %@",[self remainingTextForSeconds:eta]];self.statusLabel.text=status; }
- (void)packFinished { self.packJobID=nil;NSString *preferred=[[NSUserDefaults standardUserDefaults]stringForKey:@"selectedICAO"];self.selectedAirport=nil;[self loadOfflinePacks];if(preferred.length)[self selectAirportByCode:preferred];else if(self.allAirports.count)[self selectAirportByCode:[[self.allAirports objectAtIndex:0]objectForKey:@"ident"]];self.statusLabel.text=@"Charts and airport maps installed"; }
- (void)packFailed { self.statusLabel.text=@"Pack transfer failed; partial files removed"; }

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)orientation { return YES; }
- (void)dealloc { [_topBar release];[_footer release];[_categoryRail release];[_airportButton release];[_airportCaptionLabel release];[_searchField release];[_searchButton release];[_settingsButton release];[_mapButton release];[_weatherButton release];[_fitButton release];[_previousButton release];[_nextButton release];[_titleLabel release];[_statusLabel release];[_categoryTable release];[_airportTable release];[_chartTable release];[_scrollView release];[_imageView release];[_allAirports release];[_airports release];[_categories release];[_chartGroups release];[_selectedAirport release];[_selectedChart release];[_chartPages release];[_packJobID release];[super dealloc]; }
@end
