#import "ContentManagerViewController.h"

@interface ContentManagerViewController ()
@property(nonatomic, retain) UITableView *tableView;
@property(nonatomic, retain) NSArray *rows;
@end

@implementation ContentManagerViewController
@synthesize tableView=_tableView,rows=_rows;

- (void)viewDidLoad { [super viewDidLoad];self.title=@"Downloaded Content";self.navigationItem.rightBarButtonItem=[[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(done)]autorelease];self.tableView=[[[UITableView alloc]initWithFrame:self.view.bounds style:UITableViewStyleGrouped]autorelease];self.tableView.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight;self.tableView.dataSource=self;self.tableView.delegate=self;[self.view addSubview:self.tableView];[self reloadContent]; }
- (void)done { [self dismissModalViewControllerAnimated:YES]; }
- (void)reloadContent { NSString *root=@"/var/mobile/Library/AtlasSix/ChartPacks";NSMutableArray *rows=[NSMutableArray array];NSArray *directories=[[[NSFileManager defaultManager]contentsOfDirectoryAtPath:root error:NULL]sortedArrayUsingSelector:@selector(caseInsensitiveCompare:)];for(NSString *directory in directories){NSString *packPath=[root stringByAppendingPathComponent:directory];NSData *data=[NSData dataWithContentsOfFile:[packPath stringByAppendingPathComponent:@"pack.json"]];NSDictionary *manifest=data?[NSJSONSerialization JSONObjectWithData:data options:0 error:NULL]:nil;if(!manifest)continue;NSArray *airports=[manifest objectForKey:@"airports"]?:[NSArray array];[rows addObject:[NSDictionary dictionaryWithObjectsAndKeys:[manifest objectForKey:@"name"]?:directory,@"title",[NSString stringWithFormat:@"%@ package • %lu airports",[manifest objectForKey:@"country"]?:@"Custom",(unsigned long)airports.count],@"subtitle",@0,@"level",@"pack",@"type",packPath,@"path",nil]];NSString *lastRegion=nil,*lastCity=nil;NSArray *sorted=[airports sortedArrayUsingComparator:^NSComparisonResult(id a,id b){NSString *ka=[NSString stringWithFormat:@"%@|%@|%@",[a objectForKey:@"region"]?:@"",[a objectForKey:@"city"]?:@"",[a objectForKey:@"ident"]?:@""];NSString *kb=[NSString stringWithFormat:@"%@|%@|%@",[b objectForKey:@"region"]?:@"",[b objectForKey:@"city"]?:@"",[b objectForKey:@"ident"]?:@""];return[ka compare:kb];}];for(NSDictionary *airport in sorted){NSString *region=[airport objectForKey:@"region"]?:@"Unknown Region",*city=[airport objectForKey:@"city"]?:@"Unknown City";if(![region isEqual:lastRegion]){[rows addObject:[NSDictionary dictionaryWithObjectsAndKeys:region,@"title",@"State / province / region",@"subtitle",@1,@"level",@"group",@"type",nil]];lastRegion=region;lastCity=nil;}if(![city isEqual:lastCity]){[rows addObject:[NSDictionary dictionaryWithObjectsAndKeys:city,@"title",@"City",@"subtitle",@2,@"level",@"group",@"type",nil]];lastCity=city;}[rows addObject:[NSDictionary dictionaryWithObjectsAndKeys:[NSString stringWithFormat:@"%@ — %@",[airport objectForKey:@"ident"]?:@"",[airport objectForKey:@"name"]?:@""],@"title",@"Airport charts",@"subtitle",@3,@"level",@"airport",@"type",nil]];}}self.rows=rows;[self.tableView reloadData]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)table { return 1; }
- (NSInteger)tableView:(UITableView *)table numberOfRowsInSection:(NSInteger)section { return self.rows.count; }
- (UITableViewCell *)tableView:(UITableView *)table cellForRowAtIndexPath:(NSIndexPath *)path { UITableViewCell *cell=[table dequeueReusableCellWithIdentifier:@"content"];if(!cell)cell=[[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"content"]autorelease];NSDictionary *row=[self.rows objectAtIndex:path.row];NSInteger level=[[row objectForKey:@"level"]integerValue];cell.indentationLevel=level;cell.indentationWidth=18;cell.textLabel.text=[row objectForKey:@"title"];cell.detailTextLabel.text=[row objectForKey:@"subtitle"];cell.textLabel.font=[UIFont fontWithName:level==0?@"Helvetica-Bold":@"Helvetica" size:level==0?18:15];cell.selectionStyle=UITableViewCellSelectionStyleNone;return cell; }
- (BOOL)tableView:(UITableView *)table canEditRowAtIndexPath:(NSIndexPath *)path { return [[[self.rows objectAtIndex:path.row]objectForKey:@"type"]isEqual:@"pack"]; }
- (UITableViewCellEditingStyle)tableView:(UITableView *)table editingStyleForRowAtIndexPath:(NSIndexPath *)path { return UITableViewCellEditingStyleDelete; }
- (NSString *)tableView:(UITableView *)table titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)path { return @"Delete Pack"; }
- (void)tableView:(UITableView *)table commitEditingStyle:(UITableViewCellEditingStyle)style forRowAtIndexPath:(NSIndexPath *)path { if(style!=UITableViewCellEditingStyleDelete)return;NSDictionary *row=[self.rows objectAtIndex:path.row];NSString *packPath=[[row objectForKey:@"path"]copy];self.tableView.userInteractionEnabled=NO;self.navigationItem.prompt=@"Deleting chart package…";[self performSelectorInBackground:@selector(deletePackBackground:)withObject:[packPath autorelease]]; }
- (void)deletePackBackground:(NSString *)packPath { NSAutoreleasePool *pool=[[NSAutoreleasePool alloc]init];[[NSFileManager defaultManager]removeItemAtPath:packPath error:NULL];[self performSelectorOnMainThread:@selector(deletePackFinished)withObject:nil waitUntilDone:NO];[pool drain]; }
- (void)deletePackFinished { self.navigationItem.prompt=nil;self.tableView.userInteractionEnabled=YES;[self performSelector:@selector(reloadContent)withObject:nil afterDelay:0]; }
- (void)dealloc { [_tableView release];[_rows release];[super dealloc]; }
@end
